api:
  host: postservice-api
  port: 9001

loader:
  host: postservice-loader
  port: 9002
  loadUrl: https://gorest.co.in/public/v1/posts

grud:
  host: postservice-grud
  port: 9003

database:
  postgres:
    host: postservice-db
    port: 5432
    dbname: postservice
    username: postservice
    password: abcd1234